README.md
app/build.gradle.kts
app/src/androidTest/java/com/android/voyageur/ExampleInstrumentedTest.kt
app/src/androidTest/java/com/android/voyageur/screen/MainScreen.kt
app/src/main/java/com/android/voyageur/MainActivity.kt
app/src/main/java/com/android/voyageur/SecondActivity.kt
app/src/main/java/com/android/voyageur/SimpleData.kt
app/src/main/java/com/android/voyageur/model/location/Location.kt
app/src/main/java/com/android/voyageur/model/trip/Trip.kt
app/src/main/java/com/android/voyageur/resources/C.kt
app/src/main/java/com/android/voyageur/ui/theme/Color.kt
app/src/main/java/com/android/voyageur/ui/theme/Theme.kt
app/src/main/java/com/android/voyageur/ui/theme/Type.kt
app/src/test/java/com/android/voyageur/ExampleRobolectricTest.kt
app/src/test/java/com/android/voyageur/ExampleUnitTest.kt
app/src/test/java/com/android/voyageur/PointTest.kt
app/src/test/java/com/android/voyageur/screen/SecondScreen.kt
gradle/libs.versions.toml

PR for issue [#19]
In this PR:
- changed app name from `com.android.sample` to `com.android.voyageur`
- added the data classes for `Location` and `Trip`
- added firebase dependencies ( needed for `Timestamp` class )
Note:
The activity model is not yet finalised, so when instantiating this class just use an empty array for the `activities` field

Create trip model

---

app/build.gradle.kts
app/src/main/java/com/android/voyageur/App.kt
app/src/main/java/com/android/voyageur/MainActivity.kt
app/src/main/java/com/android/voyageur/model/trip/Trip.kt
app/src/main/java/com/android/voyageur/model/trip/TripsViewModel.kt
app/src/main/java/com/android/voyageur/ui/overview/AddTrip.kt
app/src/test/java/com/android/voyageur/model/trip/TripRepositoryFirebaseTest.kt
app/src/test/java/com/android/voyageur/model/trip/TripsViewModelTest.kt
build.gradle.kts
gradle/libs.versions.toml

This feature wants to merge the feat/add-trip-screen branch to feat/home-screen-UI branch to update the Overview Screen with the trips fetched from firebase directly (instead of mockup trips).

Merge feat/add trip screen and feat/home-screen-UI

---

.github/workflows/CI.yaml
app/build.gradle.kts

This should upload the coverage reports to the sonar cloud.

Upload coverage to sonar cloud

---

app/src/main/java/com/android/voyageur/model/activity/Activity.kt
app/src/main/java/com/android/voyageur/model/trip/Trip.kt

Add a base activity model and integrate it in the existing trip model
- **Models:**: Trip model that has the following fields: 
```
- title
- description
- location
- startTime
- endDate
- estimatedPrice
- activityType
```
No need for testing as this is just a simple data class, but nevertheless the existing tests are still passing
Closes #49

feat: Add activity model

---

.github/workflows/build.yaml

Create the build workflow file

Add Build APK workflow

---

.github/workflows/build.yaml

Change the artifact uploader version used

fix: change upload artifcat version

---

.github/workflows/build.yaml
app/src/main/AndroidManifest.xml
app/src/main/java/com/android/voyageur/MainActivity.kt
app/src/main/java/com/android/voyageur/ui/theme/Theme.kt
app/src/main/res/values-night/themes.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/themes.xml
settings.gradle.kts

There is no good way to test this without removing the ruleset, because it requires the workflow to be on main.
So there might be repetite PRs.
Also changed the name of the app in the build

Add Env Variable to workflow

---

app/src/androidTest/java/com/android/voyageur/ui/theme/VoyageurThemeTest.kt
app/src/test/java/com/android/voyageur/model/activity/ActivityTest.kt
app/src/test/java/com/android/voyageur/model/location/LocationTest.kt
app/src/test/java/com/android/voyageur/model/trip/TripRepositoryFirebaseTest.kt
app/src/test/java/com/android/voyageur/model/trip/TripsViewModelTest.kt
app/src/test/java/com/android/voyageur/model/user/UserTest.kt
app/src/test/java/com/android/voyageur/ui/navigation/NavigationActionsTest.kt

This PR simply adds tests to expand code coverage on various classes
Closes #90 
Ran grade check and connectedCheck commands to ensure test pass

Expand code coverage

---

app/src/androidTest/java/com/android/voyageur/ui/e2e/EndToEndTest.kt

Implemented an end-to-end test which checks the navigation between the home page(overview) and all the others (and back) - search bar, creating a trip, view by day.
Closes #91

Add End-To-End Test

---

app/src/main/java/com/android/voyageur/model/user/UserRepositoryFirebase.kt

Made the user search case insensitive as established during the meetings.
- **Repositories:** Modified the searchUsers function in the UserRepositoryFirebase class
Previous tests on the search function still pass
Closes #120

fix: case insensitive user search

---

app/src/main/java/com/android/voyageur/ui/TimePickers.kt
app/src/main/java/com/android/voyageur/ui/formFields/DatePicker.kt
app/src/main/java/com/android/voyageur/ui/formFields/TimePicker.kt
app/src/main/java/com/android/voyageur/ui/overview/AddTrip.kt
app/src/main/java/com/android/voyageur/ui/trip/AddActivity.kt

In order to avoid code duplication and because the date picker and time picker are needed for more screens, I created a new file and moved them there.
Closes #127

Create separate file for time pickers

---

app/src/androidTest/java/com/android/voyageur/ui/trip/activities/ActivitiesScreenTest.kt
app/src/main/java/com/android/voyageur/model/activity/Activity.kt
app/src/main/java/com/android/voyageur/ui/trip/Tabs.kt
app/src/main/java/com/android/voyageur/ui/trip/activities/Activities.kt
app/src/main/java/com/android/voyageur/ui/trip/schedule/ByDay.kt

This change improves some aspects that relate to activities:
1. Activities screen uses the trip activities instead of hardcoded values
2. Draft activities don't appear on the ByDay screen (before they were appearing as 1970/01/01)
3. Activities are now displayed in chronological order, both in the ByDay screen and Activities screen
4. The Activities screen now has an 'Add Activity' button 
5. Added tests
#130

Feat Improvements to Activities

---

app/src/androidTest/java/com/android/voyageur/ui/trip/schedule/ByDayScreenTest.kt
app/src/main/java/com/android/voyageur/ui/trip/schedule/ByDay.kt

This PR introduces unit tests for the ByDay Screen composable, as well as cleaning the code (removes commented lines mentioned in previous PR #105), adding comments and finalising the screen. 
- **Bug Fixes/Improvements:** This PR adds tests for the Screen and the helper functions it uses.
This PR addresses #130.
Not applicable.
No additional context.

Test: Add tests for ByDay screen.

---

app/src/main/java/com/android/voyageur/ui/trip/AddActivity.kt

Cannot create an activity if the date is not between the start date and end date of the trip (included).
- **Bug Fixes/Improvements:** Solves #141 
Closes #141 
https://github.com/user-attachments/assets/a89a6644-a7d8-4011-b3d2-7fbfae2d6355

fix: activity date is between trip's dates

---

app/src/main/java/com/android/voyageur/model/user/UserRepositoryFirebase.kt

Application was crashing if the contacts list was empty when fetching users.

Fix startup crash cause by empty query list

---

app/src/main/java/com/android/voyageur/ui/formFields/UserDropdown.kt
app/src/main/java/com/android/voyageur/ui/overview/AddTrip.kt

Fix the color scheme and spacing regarding the participants field in Add Trip.
- **Screens/UI:** Uniform border color and uniform spacing
Contributes to #150 and #160

Fix Participants UI in addTrip

---

app/build.gradle.kts
app/src/androidTest/java/com/android/voyageur/ui/overview/AddTripTest.kt
app/src/androidTest/java/com/android/voyageur/ui/profile/EditProfileScreenTest.kt
app/src/androidTest/java/com/android/voyageur/ui/search/SearchUserProfileTest.kt
app/src/androidTest/java/com/android/voyageur/ui/utils/ImageCopperUtilTest.kt
app/src/main/java/com/android/voyageur/ui/gallery/PermissionButtonForGallery.kt
app/src/main/java/com/android/voyageur/ui/overview/AddTrip.kt
app/src/main/java/com/android/voyageur/ui/overview/Overview.kt
app/src/main/java/com/android/voyageur/ui/profile/EditProfileScreen.kt
app/src/main/java/com/android/voyageur/ui/search/SearchScreen.kt
app/src/main/java/com/android/voyageur/ui/utils/ImageCropperUtil.kt

This PR introduces various UI improvements and consistency fixes across several screens to enhance user experience and visual coherence. Adds also a new feature, image cropping in AddTripScreen and EditProfileScreen when choosing a photo from the galley
Overview Screen
- Implemented consistent color schemes for light/dark themes
- Made trip cards responsive with adaptable sizing
- Standardized date format display
Edit Profile Screen
- Removed redundant "Add" button
- Added placeholder text: "Press Enter to add interest"
- Enlarged interest input bar to match other field sizes
Add Trip Screen
- Added image cropping functionality for trip photos
- Fixed image selection button placement
- Improved overall layout consistency
Search User Screen
- Implemented light/dark theme color schemes
- …

UI/UX Enhancements Across Multiple Screens

---

app/src/androidTest/java/com/android/voyageur/ui/e2e/EndToEndTestM2.kt
app/src/main/java/com/android/voyageur/ui/trip/schedule/TopBarWithImage.kt

This PR contains the second end-to-end test for our app. This comprehensive test checks that all screens and elements are displayed as they should and also checks the navigation between the screens. It also tests the creation of a trip, searching users/places, editing fields and profile, mocking all the necessary actions.
- **Models:** Added testTag for goBack button in TopBarWithImage
- **Bug Fixes/Improvements:** #159 
Closes #159

EndToEndTest for M2

---

app/src/androidTest/java/com/android/voyageur/ui/e2e/EndToEndTest.kt
app/src/androidTest/java/com/android/voyageur/ui/e2e/EndToEndTestM2.kt
app/src/androidTest/java/com/android/voyageur/ui/trip/TobTabsTest.kt
app/src/androidTest/java/com/android/voyageur/ui/trip/settings/SettingsScreenTest.kt
app/src/main/java/com/android/voyageur/App.kt
app/src/main/java/com/android/voyageur/model/trip/TripRepositoryFirebase.kt
app/src/main/java/com/android/voyageur/model/user/UserViewModel.kt
app/src/main/java/com/android/voyageur/ui/overview/AddTrip.kt
app/src/main/java/com/android/voyageur/ui/overview/Overview.kt
app/src/main/java/com/android/voyageur/ui/trip/Tabs.kt
app/src/main/java/com/android/voyageur/ui/trip/settings/Settings.kt
app/src/test/java/com/android/voyageur/model/trip/TripRepositoryFirebaseTest.kt

In this PR I solved #181 and #182.
So now after you add a trip you can add participants using a dropdown menu. If somebody else added you as a participant, you will be able to see that trip as well on your overview screen.
- **Bug Fixes/Improvements:** Bugfix regarding the UI

Improve participants selection and show trips you are participating in

---

app/src/androidTest/java/com/android/voyageur/ui/overview/OverviewScreenTest.kt
app/src/main/java/com/android/voyageur/model/trip/TripsViewModel.kt
app/src/main/java/com/android/voyageur/ui/overview/Overview.kt

This PR introduces the possibility to delete a trip. I will attach a screen recording to present the process which is built in a user friendly mode.
- **Screens/UI:** The user can now delete a trip
- **Bug Fixes/Improvements:** Addresses #190 
Closes #190 
https://github.com/user-attachments/assets/61403abf-a1c7-4fe4-9dcc-aaa9eb8fc340

add delete trip functionality

---

app/src/main/java/com/android/voyageur/ui/profile/ProfileScreen.kt
app/src/main/java/com/android/voyageur/ui/search/SearchScreen.kt

This PR fixes the dark theme UI in the Profile Screen and the search bar is limited to one row, i.e. when you press enter you don't go on the next row.
- **Screens/UI:** Dark Theme in Profile Screen, functionality of search bar

Fix/adjustments UI

---

app/src/androidTest/java/com/android/voyageur/ui/search/SearchUserProfileTest.kt
app/src/main/java/com/android/voyageur/model/notifications/FriendRequestRepository.kt
app/src/main/java/com/android/voyageur/model/notifications/FriendRequestRepositoryFirebase.kt
app/src/main/java/com/android/voyageur/model/user/UserViewModel.kt
app/src/main/java/com/android/voyageur/ui/components/UserProfileContent.kt
app/src/main/java/com/android/voyageur/ui/profile/EditProfileScreen.kt
app/src/main/java/com/android/voyageur/ui/search/SearchScreen.kt
app/src/main/java/com/android/voyageur/ui/search/SearchUserProfile.kt

This PR introduces several enhancements to improve user experience and streamline contact management:
- Back Button for Edit Profile Screen: Added a back navigation button to the Edit Profile screen, allowing users to easily return to their Profile screen.
- Enhanced Contact Management in Search Screen:
- Add/Remove Contacts: Updated the "Add Contact" button in the search results to toggle between "Add", "Requested", and "Remove" states based on the contact's status.
- Friend Request Status: The button now displays:
- "Requested" when a friend request has been sent but not yet accepted.
- "Remove" when the user is already in contacts.
- "Add" when the user is not in contacts and no friend request has been sent.
- These changes enhance the app's usability by providing immediate feedback on …

Back button for edit profile and remove contact from search

---

app/src/main/java/com/android/voyageur/ui/formFields/DatePicker.kt
app/src/main/java/com/android/voyageur/ui/formFields/TimePicker.kt
app/src/main/java/com/android/voyageur/ui/overview/AddTrip.kt
app/src/main/java/com/android/voyageur/ui/trip/AddActivity.kt
app/src/main/java/com/android/voyageur/ui/trip/activities/EditActivity.kt
app/src/main/res/values/strings.xml

Added documentation and replaced the hardcoded strings in the following files: addTrip, addActivity, datePicker, timePicker, editActivity
- **Bug Fixes/Improvements:** add documentation + replace hardcoded strings in order to improve code readability 

add documentation + remove hardcoded strings

---

app/src/main/java/com/android/voyageur/ui/overview/Overview.kt
app/src/main/java/com/android/voyageur/ui/trip/activities/Activities.kt

This PR standardizes the layout of the search bar across various screens by utilizing the SearchBar composable introduced in a previous PR.
- **Screens/UI:** 
OverviewScreen: changed search bar
ActivitiesScreen: changed search bar
Note: no tests have been added since no change in code logic has been done

Fix: standardization search bar
