swent-t16/Voyageur

app/src/androidTest/java/com/android/voyageur/ui/search/SearchScreenTest.kt
app/src/main/java/com/android/voyageur/App.kt
app/src/main/java/com/android/voyageur/ui/search/SearchScreen.kt

- Implement search functionality in SearchScreen, allowing users to search for other users by their name, searching for locations will be implemented in a future commit
- Implmented filtering for search results, allowing users to filter for users, location, or all (currently filtering for locations displays a message that the functionality is not yet implemented)
- Added tests for the search and filter functionalities in SearchScreen
- Note that support for searching for locations will be added in the future as we need to integrate the Google Places API first
- **Screens/UI:** Implemented functionality in the search screen, see recording below for the changes.
This feature was tested manually using an emulated …

feat(ui:search-page): add functionality to SearchScreen

---

app/src/main/java/com/android/voyageur/ui/overview/AddTrip.kt

This PR aims to fix a bug, which currently allows the user to leave the participant field as empty, but instead of setting the participant list as an empty list, it puts an empty string as a participant. This causes the Overview screen to fail when a card is trying to display the box with the participant's first letter. Further, if the text field is left empty, there should be an empty list, not an empty string set as the participant list.
- **Screens/UI:** Changes the participant list in AddTrip Screen.
- **Bug Fixes/Improvements:**  Now the participant list is an emptyList(), not an empty string if the text field is left empty.
This issue was previously resolved in PR #73, but for some reason it got overwritten in main, so I am fixing it again.

fix: Solve the AddTrip participant list when input is empty.

---

app/src/androidTest/java/com/android/voyageur/ui/trip/schedule/ByDayScreenTest.kt
app/src/main/java/com/android/voyageur/ui/trip/Tabs.kt
app/src/main/java/com/android/voyageur/ui/trip/schedule/ByDay.kt
app/src/main/java/com/android/voyageur/ui/trip/schedule/TopBarWithImage.kt

This PR implements the ByDay Screen with a top app bar which contains the image of a trip. It displays each day with activities as a card, and the activities inside the card. For the moment, activities displayed are hard-coded as the possibility of adding activities is not yet implemented.
If there are no activities, it displays a text which suggests to the user to add activities.
- **Screens/UI:** The ByDay Screen now correctly displays Cards which contain the days and the list of activities for each day.
-  Unit Tests …

Feat: ByDay Screen.

---

app/src/androidTest/java/com/android/voyageur/ui/overview/AddTripTest.kt
app/src/androidTest/java/com/android/voyageur/ui/trip/settings/SettingsScreenTest.kt
app/src/main/java/com/android/voyageur/model/trip/TripsViewModel.kt
app/src/main/java/com/android/voyageur/ui/overview/AddTrip.kt
app/src/main/java/com/android/voyageur/ui/trip/Tabs.kt
app/src/main/java/com/android/voyageur/ui/trip/settings/Settings.kt

Add the settings screen UI which edits the selected trip
Solves #85 
- **Screens/UI:** In the `settings` tab of the trip view 
- **Repositories:** Added success callback to viewModel functions as well
- **Bug Fixes/Improvements:** List any GitHub issues this PR addresses or any improvements to the existing codebase.

feat: add edit mode

---

.github/workflows/CI.yaml
.github/workflows/build.yaml
app/build.gradle.kts
app/src/androidTest/java/com/android/voyageur/ui/search/SearchScreenTest.kt
app/src/main/AndroidManifest.xml
app/src/main/java/com/android/voyageur/model/place/GooglePlacesRepository.kt
app/src/main/java/com/android/voyageur/ui/search/SearchScreen.kt
gradle/libs.versions.toml

Refined the Search Page to look like the Mockup provided in the figma.
- **Screens/UI:** 2 tabs are now present (Users and Places), also when in places tab we can toggle between map view and list view, also changed what composables are show for each user and each place.
- **Repositories:** Added lat_lng Place field in the Places API request to be able to display a pin in the map view for each place.
Closes #59

Feat/search page UI upgrade

---

app/src/main/java/com/android/voyageur/ui/search/SearchScreen.kt

Remove the location update interval after the first non null location update.
- **Bug Fixes/Improvements:** The bug was causing the map to recenter everytime the person moved and resulted in a bad user experience. This is not testable on an emulator, but you can see it on a physical android phone.

Remove the interval after the first successfull update

---

app/src/androidTest/java/com/android/voyageur/ui/profile/EditProfileScreenTest.kt
app/src/androidTest/java/com/android/voyageur/ui/profile/ProfileScreenTest.kt
app/src/androidTest/java/com/android/voyageur/ui/profile/interests/InterestChipEditableTest.kt
app/src/androidTest/java/com/android/voyageur/ui/profile/interests/InterestChipTest.kt
app/src/main/java/com/android/voyageur/model/user/User.kt
app/src/main/java/com/android/voyageur/ui/profile/EditProfileScreen.kt
app/src/main/java/com/android/voyageur/ui/profile/ProfileScreen.kt
app/src/main/java/com/android/voyageur/ui/profile/interests/InterestChip.kt
app/src/main/java/com/android/voyageur/ui/profile/interests/InterestChipEditable.kt
app/src/test/java/com/android/voyageur/model/user/UserTest.kt
app/src/test/java/com/android/voyageur/model/user/UserViewModelTest.kt
app/src/test/java/com/android/voyageur/ui/profile/FindActivityTest.kt

This PR adds support for managing user interests within the app, allowing users to view, add, and remove their interests. Interests are now displayed both in the ProfileScreen and EditProfileScreen. The implementation includes UI components for displaying and editing interests, as well as unit and UI tests to ensure functionality and reliability. Significant enhancements have also been made to the UserViewModel and related classes to support these new features. The associated tests have been updated and expanded to cover the new functionalities.
- **Screens/UI:** 
- ProfileScreen:
- Interest Display:
- Updated to display the user's interests as chips, providing a personalized overview of the user's profile.
- Used the InterestChip composable to render each interest.
- EditProfileScreen:
- …

feat: add support for interests in the profile screen + tests

---

app/src/androidTest/java/com/android/voyageur/ui/search/SearchScreenTest.kt
app/src/main/java/com/android/voyageur/model/place/GooglePlacesRepository.kt
app/src/main/java/com/android/voyageur/model/place/PlacesRepository.kt
app/src/main/java/com/android/voyageur/model/place/PlacesViewModel.kt
app/src/main/java/com/android/voyageur/ui/search/SearchScreen.kt

In this PR I address the issue #118.
If the user has granted the necessary permissions, we will only search / filter the places in a small radius centered around the user location.
If the user has not granted location permissions, the default location will be used / no boundaries applied => it will show places all around the globe.
If the user has granted permissions but has location disabled, a dialog will pop up to request the user to enable the location in the settings
- **Repositories:** Updated the repository for places ( and googlesearch repo) to allow an optional location parameter
- **Bug Fixes/Improvements:** Fix the user pin and enable the maps recenter properties.
- [] Tests have been added for new …

Feat: add nearby search

---

app/src/main/java/com/android/voyageur/ui/overview/AddTrip.kt

Fixed a bug where the activities would dissapear from the trip when saving the trip in the settings screen.
Solves #138

Fix: add trip screen keep activities

---

app/src/androidTest/java/com/android/voyageur/ui/trip/AddActivityTest.kt
app/src/main/java/com/android/voyageur/ui/trip/AddActivity.kt

When creating an activity, if you selected just the date and no startTime/endTime it was creating the activity at timestamp(0, 0). Now, it is created at the specified date (at midnight).
If not selected, set default startTime to 00:00 and endTime to 23:59. Moreover, we decided that you cannot have activities created just with endTime, but you can have activities created only with a startTime.
- **Bug Fixes/Improvements:** 
- #132 
- #134 
Closes #132 …

fix behavior when selecting only the date

---

app/src/androidTest/java/com/android/voyageur/ui/trip/TobTabsTest.kt
app/src/main/java/com/android/voyageur/ui/trip/Tabs.kt

This pull request fixes a bug in the TopTabs composable where an error occurred if the selected trip was null after modifying photo permissions. The update ensures that the app navigates back to the "Overview" screen if there is no selected trip, improving error handling and user experience. This is a bug fix aimed at gracefully handling cases where a trip may be null.
- **Screens/UI:** Updated the TopTabs composable to check if the selected trip is null. If null, it now navigates back to the "Overview" screen using NavigationActions.
- **Bug Fixes/Improvements:** Addresses the issue where modifying photo permissions could cause a null trip error in TopTabs. This fix ensures a smooth user experience when permissions are modified.
Ensure all / most of these are checked before the pull …

Fix bug TapsScreen

---

app/src/androidTest/java/com/android/voyageur/ui/profile/EditProfileScreenTest.kt
app/src/main/java/com/android/voyageur/ui/profile/EditProfileScreen.kt

This pull request fixes a bug in the EditProfileScreen composable where an error occurred if the user data was null after modifying photo permissions. The update ensures that the app navigates back to the "Profile" screen if user data is unavailable, improving error handling and the overall user experience. This is a bug fix aimed at gracefully managing cases where user data may be null.
- **Screens/UI:** Updated the EditProfileScreen composable to check if the user data is null. If null, it now navigates back to the "Profile" screen using NavigationActions.
- **Bug Fixes/Improvements:** Addresses the issue where modifying photo permissions could cause a null user error in EditProfileScreen. This fix ensures a smooth user experience when permissions are modified or user data is …

Fix bug EditProfileScreen

---

app/src/androidTest/java/com/android/voyageur/ui/overview/OverviewScreenTest.kt
app/src/androidTest/java/com/android/voyageur/ui/trip/TobTabsTest.kt
app/src/androidTest/java/com/android/voyageur/ui/trip/schedule/ScheduleScreenTest.kt
app/src/main/java/com/android/voyageur/ui/navigation/NavigationActions.kt
app/src/main/java/com/android/voyageur/ui/overview/Overview.kt
app/src/main/java/com/android/voyageur/ui/trip/Tabs.kt
app/src/main/java/com/android/voyageur/ui/trip/schedule/ScheduleScreen.kt

Previously, when navigation changed from Tob Tabs to another screen (e.g. Add Activity Screen) and the user wanted to go back, the Schedule tab with Daily view was always displayed, even if the users invoked the screen from the Activities tab, or the Weekly view.
This bugfix solves this issue. Now the navigation actions remember which tab and view is selected. This resets once we exit the trip.
- **Logic/Controllers:** NavigationActions now remembers the currentTripTab and if the daily view is selected or not.
- **Bug Fixes/Improvements:** same as summary, navigation is improved
[Screen_recording_20241111_151327.webm](https://github.com/user-attachments/assets/3d09887d-efe4-4 …

Fix remember tab navigation

---

.github/workflows/CI.yaml
.github/workflows/build.yaml

Fix the CI and build apk pipelines that didn't set the places api key correctly due to a formatting error

Fix: correctly add API key to build pipelines

---

app/src/main/java/com/android/voyageur/ui/trip/AddActivity.kt

I fixed the price field of the activity screen. You can input only numbers and with maximum 2 digits. 
- **Models:** estimatedPrice field logic in AddActivityScreen has been updated
- **Bug Fixes/Improvements:** #165
Closes #165

fix price field

---

app/src/androidTest/java/com/android/voyageur/ui/e2e/EndToEndTest.kt
app/src/androidTest/java/com/android/voyageur/ui/e2e/EndToEndTestM2.kt
app/src/androidTest/java/com/android/voyageur/ui/overview/DropDownTest.kt
app/src/androidTest/java/com/android/voyageur/ui/overview/OverviewScreenTest.kt
app/src/main/java/com/android/voyageur/model/user/UserViewModel.kt
app/src/main/java/com/android/voyageur/ui/formFields/UserDropdown.kt
app/src/main/java/com/android/voyageur/ui/overview/AddTrip.kt
app/src/main/java/com/android/voyageur/ui/overview/Overview.kt

This PR introduces improvements to the Overview Screen and to the AddParticipant screen to show the participant users' profile pictures instead of an icon which displayed their initial. If the user added to the trip has no profile picture, the icon containing their initial will be displayed. Moreover, it uses a loading screen to wait for the profile pictures to be fetched from the database.
- **Models:** Modified the `getUsersByIds() `method to update the `_isLoading` state flow value of the userViewModel.
- **Screens/UI:** Overview and Participant form in both AddTrip and Settings screens display the profile picture of the participant users instead of an icon.
- **Bug Fixes/Improvements:** This addresses #179.
Closes #179.

Feat/Display User profile icon in Overview and Participants Form.

---

app/src/androidTest/java/com/android/voyageur/ui/trip/AddActivityTest.kt
app/src/androidTest/java/com/android/voyageur/ui/trip/activities/ActivitiesScreenTest.kt
app/src/androidTest/java/com/android/voyageur/ui/trip/activities/ActivityItemTest.kt
app/src/main/java/com/android/voyageur/App.kt
app/src/main/java/com/android/voyageur/model/trip/TripsViewModel.kt
app/src/main/java/com/android/voyageur/ui/formFields/DatePicker.kt
app/src/main/java/com/android/voyageur/ui/formFields/TimePicker.kt
app/src/main/java/com/android/voyageur/ui/navigation/NavigationActions.kt
app/src/main/java/com/android/voyageur/ui/trip/AddActivity.kt
app/src/main/java/com/android/voyageur/ui/trip/Tabs.kt
app/src/main/java/com/android/voyageur/ui/trip/activities/Activities.kt
app/src/main/java/com/android/voyageur/ui/trip/activities/ActivitiesForOneDay.kt
app/src/main/java/com/android/voyageur/ui/trip/activities/ActivityItem.kt
app/src/main/java/com/android/voyageur/ui/trip/activities/EditActivity.kt

This PR introduces the feature of editing an existing activity. For each activity item, I added an edit button near the delete button which leads the user to editing the activity. The edit activity screen calls the add activity screen with an extra parameter, the already existing activity and makes the required changes.
I will attach a screen recording which presents the behavior.
- **Models:** Added tripsViewModel and navigationActions as parameters to all the activity related screens/methods
- **Screens/UI:** The edit activity screen calls the add activity screen with the fields already completed
- **Bug Fixes/Improvements:** Addresses #185 .
Explain how this feature was tested and what kind of testing (unit, …

feat: edit activity + tests

---

app/src/androidTest/java/com/android/voyageur/ui/profile/ProfileScreenTest.kt
app/src/main/java/com/android/voyageur/model/notifications/FriendRequestRepository.kt
app/src/main/java/com/android/voyageur/model/notifications/FriendRequestRepositoryFirebase.kt
app/src/main/java/com/android/voyageur/model/user/UserViewModel.kt
app/src/main/java/com/android/voyageur/ui/navigation/BottomNavigationMenu.kt
app/src/main/java/com/android/voyageur/ui/profile/ProfileScreen.kt
app/src/main/java/com/android/voyageur/ui/search/SearchScreen.kt
app/src/main/java/com/android/voyageur/ui/search/SearchUserProfile.kt
app/src/test/java/com/android/voyageur/model/user/UserViewModelTest.kt

This PR introduces Friend Requests displayed in the Profile Screen as a DropDown which opens a Dialog displaying them. The user has the option to:
accept -> user is added to contacts (displays as Added in Search Screen) and friend request is deleted.
deny -> friend request is deleted. The friend request displays the user's profile picture and their name.
- **Models:** Adapted `UserViewModel`.
- **Screens/UI:** Introduced Drop Down Menu with Dialog displaying friend requests in the Profile Screen.
- **Logic/Controllers:** `UserViewModel` now contains `deleteFriendRequest()` method and `addContact()` (re-introduced).
- **Repositories:**`FriendRequestRepositoryFirebase` now contains `deleteRequest()` method.
- **Bug Fixes/Improvements:** Addresses #200.
Ensure all / most of these are checked …

Feat/Display contact request and accept/delete

---

app/src/main/java/com/android/voyageur/ui/trip/AddActivity.kt

This PR introduces a small UI fix: the date picker shows the already selected date when you open it in edit mode for addActivityScreen.
- **Screens/UI:** addActivityScreen/editActivityScreen.
- **Bug Fixes/Improvements:** Addresses #207 .
Closes #207 
https://github.com/user-attachments/assets/5eebe66a-21ae-4142-a44a-f13443de61a7

date picker remembers selected date

---

app/src/main/java/com/android/voyageur/ui/overview/AddTrip.kt

When editing an ongoing trip, you couldn't save it because the start date was in the past. I fixed the behavior so that when editing a trip, you could save it with a start date in the past.
- **Models:** AddTripScreen
- **Bug Fixes/Improvements:** Addresses #197 
Closes #197

allow editing ongoing trip

---

app/src/main/java/com/android/voyageur/ui/trip/assistant/Assistant.kt

This PR fixes the bahavior of pressing enter in the Gemini Prompt: Instead of going to the next line, now "Enter" activates the search and the search bar is limited to one line.
- **Screens/UI:** behavior of Assistant
https://github.com/user-attachments/assets/c93c1460-0643-458a-80d9-1d1644ee586e

fix: enter activities prompt

---

app/src/main/java/com/android/voyageur/model/trip/TripsViewModel.kt
app/src/main/java/com/android/voyageur/ui/overview/AddTrip.kt
app/src/main/java/com/android/voyageur/ui/trip/AddActivity.kt

This PR introduces a fix which prevents duplicate savings. Until now, if the save button was pressed multiple times quickly enough duplicate trips would've been created and in case of the activities, the user was redirected to the Overview screen.
- **Screens/UI:** Fixes the behavior of multiple clicks on save in addActivityScreen and addTripScreen
- **Bug Fixes/Improvements:** Addresses #206 .
Closes #206

avoid duplicate savings

---

app/src/main/java/com/android/voyageur/ui/trip/AddActivity.kt

- the activity date must be between the trip's dates, even if it is in the past
This small fix removes the check for the activity date if it is in the past, and checks just for the date to be between the trip's dates. i.e. it solves the problem when creating/editing an activity during an ongoing trip.
- **Bug Fixes/Improvements:** Addresses #219 
Closes #219

activity date fix

---

app/src/androidTest/java/com/android/voyageur/ui/profile/ProfileScreenTest.kt
app/src/main/java/com/android/voyageur/model/user/UserViewModel.kt
app/src/main/java/com/android/voyageur/ui/profile/ProfileScreen.kt
app/src/main/res/values/strings.xml

This PR fixes the issue in which, after the user accepts a friend request, the dialog closed and they would have to open it again to visualize the friend requests. Now, the user views a list, which if empty displays a text saying there are no pending requests, otherwise displaying the requests. After approving a request, the request disappears but the list still stays open. If there are more than 3 friend requests, the user can scroll below to approve/deny them.
Moreover, documentation has been updated for the  ProfileScreen and UserViewModel.
- **Screens/UI:** Changes to the friend request list in ProfileScreen.
- **Bug Fixes/Improvements:** Improves user experience and addresses #215 .
Explain how this feature …

Refactor: Improve friend requests.

---

app/build.gradle.kts
app/src/androidTest/java/com/android/voyageur/ui/trip/activities/ActivitiesScreenTest.kt
app/src/main/java/com/android/voyageur/ui/trip/activities/Activities.kt
app/src/main/java/com/android/voyageur/ui/trip/activities/ActivityUtils.kt
app/src/main/res/values/strings.xml
gradle/libs.versions.toml

This PR introduces a button in the ActivitiesScreen, which when pressed, opens a dialog allowing the user to select one or more Activity types to filter the Activities displayed. When pressed confirm, dialog closes and only the filtered trips are displayed. The user is also able to de-select one or more filters previously selected.
Moreover, documentation has been updated for the ActivitiesScreen Composable.
- **Screens/UI:** Filter button appears now in ActiviesScreen, a Dialog Composable has been implemented in ActivityUtils and is displayed in ActivitiesScreen by pressing the button.
Closes #229.
https://github.com/user-attachments/assets/b5e13ddb-d829-4700-884b-4bd028406f …

Feat: Add button to filter activities by type.

---

app/src/androidTest/java/com/android/voyageur/ui/e2e/EndToEndTest.kt
app/src/androidTest/java/com/android/voyageur/ui/e2e/EndToEndTestM2.kt
app/src/androidTest/java/com/android/voyageur/ui/search/SearchScreenTest.kt
app/src/main/java/com/android/voyageur/App.kt
app/src/main/java/com/android/voyageur/model/trip/TripsViewModel.kt
app/src/main/java/com/android/voyageur/ui/navigation/NavigationActions.kt
app/src/main/java/com/android/voyageur/ui/overview/Overview.kt
app/src/main/java/com/android/voyageur/ui/search/DiscoverContent.kt
app/src/main/java/com/android/voyageur/ui/search/SearchScreen.kt
app/src/test/java/com/android/voyageur/model/trip/TripsViewModelTest.kt

This PR aims to introduce a new feature to the app. The Discover page where users can see trips that are public within the app in order to get ideas from other people.
- **Models:** Added the getFeed function in the TripViewModel.
- **Screens/UI:** Updated the Search screen to include the new Discover tab, created a new composable the DiscoverContent.
- **Logic/Controllers:**  Updated the Navigation actions class to take into account this new tab.
Tested manually on emulator also added plenty of other unit tests in different classes.
Closes #260.
Opens #277.
https://github.com/user-attachments/assets/641676cc-0fb0-4e53-a266-d144b4bcfe51
* Note that the space in the trips …

Feat/discovery page UI

---

app/src/androidTest/java/com/android/voyageur/ui/overview/OverviewScreenTest.kt
app/src/main/AndroidManifest.xml
app/src/main/java/com/android/voyageur/ui/overview/AddTrip.kt
app/src/main/java/com/android/voyageur/ui/overview/Overview.kt
app/src/main/res/values/strings.xml

This PR introduces the possibility to add a trip to google calendar by pressing the icon button at the top right of a trip and selecting "Add to calendar".  It opens an intent and redirects the user to the calendar app, where they  have pre-filled fields such as the name of the trip, description and start and end dates. Then, the user has the possibility to add the trip to their calendar or not.
Moreover, this feature comes with permission support for the calendar app, which if denied shows a toast to the user, and if accepted, redirects the user to the calendar app.
It also adds documentation for the Overview Screen and replacement of hardcoded strings with string resources.
- **Screens/UI:** A new DropDownMenuItem has been introduced to the DropDownMenu in the OverviewScreen.
- **Bug …

Feat/Add trips to google calendar.

---

app/src/androidTest/java/com/android/voyageur/ui/trip/photos/PhotosScreenTest.kt
app/src/main/java/com/android/voyageur/ui/gallery/PermissionButtonForGallery.kt
app/src/main/java/com/android/voyageur/ui/trip/photos/PhotosScreen.kt
app/src/main/res/values/strings.xml

This PR introduces the shouldCrop parameter for the gallery button, as we don't want to crop the images when we add them in the photos screen of a trip. Moreover, I made the add photo button to not be displayed when you open the photo dialog, for a better UI, and I adapted the close/delete buttons to remain fixed in the corners of the screen.
- **Screens/UI:** Adapted the photo dialog to be within the bounds of the screen and the close/delete buttons to remain in a fixed position.
- **Bug Fixes/Improvements:** Addresses #281 
Closes #281 
Attach screenshots or screen recordings that show UI changes.
https://github.com/user-attachments/assets/914a33d0-302a-455e-81e1-5c7d5ef226 …

fix: add shouldCrop parameter for gallery button

---

app/src/androidTest/java/com/android/voyageur/ui/components/PlaceSearchWidgetTest.kt
app/src/main/java/com/android/voyageur/model/trip/TripRepository.kt
app/src/main/java/com/android/voyageur/model/trip/TripRepositoryFirebase.kt
app/src/main/java/com/android/voyageur/model/trip/TripsViewModel.kt
app/src/test/java/com/android/voyageur/model/trip/TripRepositoryFirebaseTest.kt
app/src/test/java/com/android/voyageur/model/trip/TripsViewModelTest.kt

In this PR I created a listener for trips as I notice a bug where if you were in a trip with multiple participants and one of them edited the trip while you were still in the app, you wouldn't see. the changes unless you refreshed.
Also this listeners will handle new / deleted trips.
- **Logic/Controllers:** Use the listener in the TripsViewModel on auth change
- **Repositories:** Added a listener registration to the TripsRepository
- **Bug Fixes/Improvements:** #295 

Add listener for trip changes and update tests

---

app/src/main/java/com/android/voyageur/ui/overview/Overview.kt

This PR provides a quick bug fix that corrects the participants composable. This bug was observed in the Discover tab as it sometimes displayed " -1 participants". Also note that now this composable will also show the current user and will not filter him out as it used to.
- **Screens/UI:** Removed the filtering of the current user in the participants composable.
No tests were added but verified existing tests still pass.
Closes #333.

fix: correct participants composable to also include current user

---

app/src/main/java/com/android/voyageur/model/place/GooglePlacesRepository.kt

This PR provides a small bug fix that allows fetching also the latitude and longitude and display name when fetching the advanced details for a given place. This allows the get directions button to work properly as it used to always display a toast with no location found. 
- **Models:** Small change in the GooglePlacesRepository that also adds LAT_LNG and DISPLAY_NAME field to the advanced details query.
Verified old tests still pass but no new tests were added.
Closes #336 
https://github.com/user-attachments/assets/265a157a-2dba-40c3-bc41-e443bbc26442

fix: add other fields when fetching advanced details
